create table if not exists public.users (
  id integer generated by default as identity primary key,
  supabase_user_id varchar(128) not null unique,
  email varchar(320),
  full_name varchar(255),
  avatar_url text,
  auth_provider varchar(64) not null default 'google',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_users_supabase_user_id on public.users (supabase_user_id);

create table if not exists public.chats (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  title varchar(255) not null,
  summary text,
  language varchar(50),
  framework varchar(100),
  source varchar(50) not null default 'chat',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_chats_user_id on public.chats (user_id);

create table if not exists public.messages (
  id integer generated by default as identity primary key,
  chat_id integer not null references public.chats(id) on delete cascade,
  role varchar(20) not null,
  content text not null,
  metadata_json jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ix_messages_chat_id on public.messages (chat_id);

create table if not exists public.reviews (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  chat_id integer references public.chats(id) on delete set null,
  language varchar(50) not null,
  code text not null,
  result_json jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists ix_reviews_user_id on public.reviews (user_id);
create index if not exists ix_reviews_chat_id on public.reviews (chat_id);

create table if not exists public.uploads (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  chat_id integer references public.chats(id) on delete set null,
  filename varchar(255) not null,
  language varchar(50) not null,
  content text not null,
  file_type varchar(50) not null default 'code',
  mime_type varchar(100),
  storage_path text,
  extracted_text text,
  created_at timestamptz not null default now()
);

create index if not exists ix_uploads_user_id on public.uploads (user_id);
create index if not exists ix_uploads_chat_id on public.uploads (chat_id);

create table if not exists public.memories (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  key varchar(120) not null,
  value_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_memory_user_key unique (user_id, key)
);

create index if not exists ix_memories_user_id on public.memories (user_id);

alter table public.users enable row level security;
alter table public.chats enable row level security;
alter table public.messages enable row level security;
alter table public.reviews enable row level security;
alter table public.uploads enable row level security;
alter table public.memories enable row level security;

drop policy if exists "Users can read their own profile" on public.users;
create policy "Users can read their own profile"
on public.users
for select
using (supabase_user_id = auth.uid()::text);

drop policy if exists "Users can insert their own profile" on public.users;
create policy "Users can insert their own profile"
on public.users
for insert
with check (supabase_user_id = auth.uid()::text);

drop policy if exists "Users can update their own profile" on public.users;
create policy "Users can update their own profile"
on public.users
for update
using (supabase_user_id = auth.uid()::text)
with check (supabase_user_id = auth.uid()::text);

drop policy if exists "Users can read their own chats" on public.chats;
create policy "Users can read their own chats"
on public.chats
for select
using (
  exists (
    select 1
    from public.users u
    where u.id = chats.user_id
      and u.supabase_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can insert their own chats" on public.chats;
create policy "Users can insert their own chats"
on public.chats
for insert
with check (
  exists (
    select 1
    from public.users u
    where u.id = chats.user_id
      and u.supabase_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can update their own chats" on public.chats;
create policy "Users can update their own chats"
on public.chats
for update
using (
  exists (
    select 1
    from public.users u
    where u.id = chats.user_id
      and u.supabase_user_id = auth.uid()::text
  )
)
with check (
  exists (
    select 1
    from public.users u
    where u.id = chats.user_id
      and u.supabase_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can read their own messages" on public.messages;
create policy "Users can read their own messages"
on public.messages
for select
using (
  exists (
    select 1
    from public.chats c
    join public.users u on u.id = c.user_id
    where c.id = messages.chat_id
      and u.supabase_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can insert their own messages" on public.messages;
create policy "Users can insert their own messages"
on public.messages
for insert
with check (
  exists (
    select 1
    from public.chats c
    join public.users u on u.id = c.user_id
    where c.id = messages.chat_id
      and u.supabase_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can read their own reviews" on public.reviews;
create policy "Users can read their own reviews"
on public.reviews
for select
using (
  exists (
    select 1
    from public.users u
    where u.id = reviews.user_id
      and u.supabase_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can insert their own reviews" on public.reviews;
create policy "Users can insert their own reviews"
on public.reviews
for insert
with check (
  exists (
    select 1
    from public.users u
    where u.id = reviews.user_id
      and u.supabase_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can read their own uploads" on public.uploads;
create policy "Users can read their own uploads"
on public.uploads
for select
using (
  exists (
    select 1
    from public.users u
    where u.id = uploads.user_id
      and u.supabase_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can insert their own uploads" on public.uploads;
create policy "Users can insert their own uploads"
on public.uploads
for insert
with check (
  exists (
    select 1
    from public.users u
    where u.id = uploads.user_id
      and u.supabase_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can read their own memories" on public.memories;
create policy "Users can read their own memories"
on public.memories
for select
using (
  exists (
    select 1
    from public.users u
    where u.id = memories.user_id
      and u.supabase_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can upsert their own memories" on public.memories;
create policy "Users can upsert their own memories"
on public.memories
for insert
with check (
  exists (
    select 1
    from public.users u
    where u.id = memories.user_id
      and u.supabase_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can update their own memories" on public.memories;
create policy "Users can update their own memories"
on public.memories
for update
using (
  exists (
    select 1
    from public.users u
    where u.id = memories.user_id
      and u.supabase_user_id = auth.uid()::text
  )
)
with check (
  exists (
    select 1
    from public.users u
    where u.id = memories.user_id
      and u.supabase_user_id = auth.uid()::text
  )
);

insert into storage.buckets (id, name, public)
values
  ('code-uploads', 'code-uploads', false),
  ('screenshots', 'screenshots', false),
  ('attachments', 'attachments', false)
on conflict (id) do update
set name = excluded.name,
    public = excluded.public;

drop policy if exists "Users can manage their own storage objects" on storage.objects;
create policy "Users can manage their own storage objects"
on storage.objects
for all
using (
  bucket_id in ('code-uploads', 'screenshots', 'attachments')
  and auth.uid()::text = split_part(name, '/', 1)
)
with check (
  bucket_id in ('code-uploads', 'screenshots', 'attachments')
  and auth.uid()::text = split_part(name, '/', 1)
);

-- Projects table and RLS
create table if not exists public.projects (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  name varchar(255) not null,
  description text,
  language varchar(50),
  framework varchar(100),
  status varchar(50),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_projects_user_id on public.projects (user_id);

alter table public.projects enable row level security;

drop policy if exists "Users can manage their own projects" on public.projects;
create policy "Users can manage their own projects"
on public.projects
for all
using (
  exists (
    select 1 from public.users u where u.id = projects.user_id and u.supabase_user_id = auth.uid()::text
  )
)
with check (
  exists (
    select 1 from public.users u where u.id = projects.user_id and u.supabase_user_id = auth.uid()::text
  )
);

-- Fixes table and RLS
create table if not exists public.fixes (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  chat_id integer references public.chats(id) on delete set null,
  review_id integer references public.reviews(id) on delete set null,
  original_code text not null,
  fixed_code text not null,
  explanation text,
  validation_json jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ix_fixes_user_id on public.fixes (user_id);

alter table public.fixes enable row level security;

drop policy if exists "Users can manage their own fixes" on public.fixes;
create policy "Users can manage their own fixes"
on public.fixes
for all
using (
  exists (
    select 1 from public.users u where u.id = fixes.user_id and u.supabase_user_id = auth.uid()::text
  )
)
with check (
  exists (
    select 1 from public.users u where u.id = fixes.user_id and u.supabase_user_id = auth.uid()::text
  )
);

-- Audit logs (service role should write; keep readable only by admins)
create table if not exists public.audit_logs (
  id integer generated by default as identity primary key,
  user_id integer references public.users(id) on delete set null,
  action varchar(100) not null,
  entity_type varchar(100),
  entity_id integer,
  metadata jsonb,
  created_at timestamptz not null default now()
);
